#pragma config(Sensor, S2,     lightR,         sensorLightActive)
#pragma config(Sensor, S3,     lightL,         sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "steering.h"

task main() {
	//writeDebugStreamLine("Starting NXT");
	//steer(left);

//Kp = 10                               ! Initialize our three variables
//offset = 45
//Tp = 50
//Loop forever
//   LightValue = read light sensor     ! what is the current light reading?
//   error = LightValue - offset        ! calculate the error by subtracting the offset
//   Turn = Kp * error                  ! the "P term", how much we want to change the motors' power
//   powerA = Tp + Turn                 ! the power level for the A motor
//   powerC = Tp - Turn                 ! the power level for the C motor
//   MOTOR A direction=forward power=powerA ! issue the command with the new power level in a MOTOR block
//   MOTOR C direction=forward power=powerC ! same for the other motor but using the other power level
//end loop forever                      ! done with this loop, go back to the beginning and do it again

	//int kp = 10;
	//int offset = 45;
	//int tp = 100;

	int whiteValue = 64;
	int power = 75;
	
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;

	while (1) {
		int lightvalL = SensorValue(lightL);
		int lightvalR = SensorValue(lightR);
		int errorLeft = lightvalL - 64;
		int errorRight = lightvalR - 64;
		int powerLeft = power + (errorLeft * 200 / 64);
		int powerRight = power + (errorRight * 200 / 64);
		
		int sonarValue = SensorValue(sonar);
		
		if(powerLeft == 0 && powerRight == 0) {
			wait1Msec(1000);
			playSoundFile("! Startup.rso");
			motor[rightMotor] = 80;
			motor[leftMotor] = 80;
			wait1Msec(500);
		}
		
		if(sonarValue < 20){
			for (int i = (powerLeft + powerRight) / 2; i > 0; i--) {
				motor[leftMotor] = i;
				motor[rightMotor] = i;
				wait1Msec(10);
			}
			
			for (int i = 0; i < 50; i++) {
				motor[leftMotor] = 20;
				motor[rightMotor] = -30;
				
				if (SensorValue(lightL) < 50 && i > 20) {
					motor[leftMotor] = 0;
					motor[rightMotor] = 0;
					break;
				}
				
				wait1Msec(100);
			}
			
			//powerLeft = 0;
			//powerRight = 0;
  	}
    
   	motor[leftMotor] = powerLeft;
		motor[rightMotor] = powerRight;
	}
}