#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S2,     light,          sensorLightActive)
#pragma config(Sensor, S3,     light2,         sensorColorNxtFULL)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, openLoop, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, openLoop, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Line Track for Distance
This program uses 1 NXT Line Follower Sensor to track a black line on a light(er) surface
for 5 rotations of the encoders. There is a two second pause at the beginning of the program.

The threshold variable defined in this program may need to be changed for the line/surface your
robot is tracking and the lighting conditions.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          NXT Motor             Right side motor
Motor Port 3        leftMotor           NXT Motor             Left side motor
Sensor Port S3      lightSensor         NXT Line Follower     Back, Right, facing down
Sensor port S2 			soundSensor					NXT Line Follower			Back, Left, facing down
----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  int threshold = 40;       /* found by taking a reading on both DARK and LIGHT    */
                            /* surfaces, adding them together, then dividing by 2. */

  nMotorEncoder[rightMotor] = 0;  // Reset the right motor encoder to 0.
while(true){
  playSoundFile("! Startup.rso");
	motor[rightMotor] = 100;
	motor[leftMotor] = 100;
    if(SensorValue(light) < threshold){
      // counter-steer left:
      motor[rightMotor] = 0;
      motor[leftMotor] = 80;
    }
    if(SensorValue(light2) == BLACKCOLOR){
    	motor[leftMotor] = 0;
    	motor[rightMotor] = 80;
  	}
  	if(SensorValue(sonar) < 20){
  		playSoundFile("Woops.rso");
  		motor[leftMotor] = 0;
  		motor[rightMotor] = 0;
  		break;
    }
 	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
